import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Stack from "../../../sdk-plugins/index";
import Layout from "components/Layout/Layout";
import Image from "next/image";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function blogs({ pagedata }) {
  console.log(pagedata, "pagedata");
  return (
    <>
      <Head>
        <title>Blogs </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Layout>
          <div className="container row m-auto">
            <h1 className="text-center p-4">Blogs</h1>
            {pagedata.map((item) => (
              <div
                key={item.id}
                className={" col-md-12 col-lg-4 mb-4 mb-lg-0 p-2 "}
              >
                <Link
                  className="text-decoration-none"
                  href={`/blogs/${item.uid}`}
                >
                  <div className={" p-3 border bg-light text-center"}>
                    <Image
                      src={item.blog_image?.url}
                      width={210}
                      height={280}
                      alt="product_img"
                    />
                    <h4 className="p-2 text-decoration-none">{item.title}</h4>
                    <button className="btn btn-primary">Read More</button>
                  </div>
                </Link>
              </div>
            ))}
          </div>
        </Layout>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const result = await Stack.getEntry("blog", "en-us");
  const carousel = await Stack.getEntry("carousel", "en-us");
  const twocolumntile = await Stack.getEntry("twocolumntile", "en-us");
  const cta = await Stack.getEntry("cta", "en-us");

  return {
    props: {
      pagedata: result[0] || [],
      carouselData: carousel[0][0] || [],
      twocolumntileData: twocolumntile[0][0] || [],
      ctaData: cta[0][0] || [],
    },
  };
}
